language: node_js
node_js:
- node
- lts/*
before_script: npm install coveralls
script: make COVERAGE=1 check
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- rm -rf ./coverage
